# Generated by Django 3.0.7 on 2021-04-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адресы'},
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Россия', max_length=120),
        ),
    ]
