# Generated by Django 3.0.7 on 2021-04-28 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20210429_0036'),
        ('addresses', '0002_auto_20210418_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(max_length=120, verbose_name='Строка адреса 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Строка адреса 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=120, verbose_name='Тип адреса'),
        ),
        migrations.AlterField(
            model_name='address',
            name='billing_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.BillingProfile', verbose_name='Платёжный адрес'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=120, verbose_name='Город или населенный пункт'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Россия', max_length=120, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=120, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=120, verbose_name='Федеративная единица или штат'),
        ),
    ]
