# Generated by Django 3.0.7 on 2021-04-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingprofile',
            options={'verbose_name': 'Профиль оплаты', 'verbose_name_plural': 'Профили оплаты'},
        ),
    ]
