# Generated by Django 3.0.7 on 2021-04-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200204_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestemail',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='guestemail',
            name='active',
        ),
        migrations.RemoveField(
            model_name='guestemail',
            name='created_at',
        ),
        migrations.AddField(
            model_name='guestemail',
            name='full_name',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestemail',
            name='reason',
            field=models.TextField(default='no reason'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guestemail',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='superuser',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
    ]
