# Generated by Django 3.0.7 on 2021-04-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210418_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestemail',
            name='full_name',
            field=models.CharField(max_length=240, verbose_name='Имя'),
        ),
    ]
