# Generated by Django 3.0.7 on 2021-04-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210428_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestemail',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
        migrations.AlterField(
            model_name='guestemail',
            name='full_name',
            field=models.CharField(max_length=240, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='guestemail',
            name='reason',
            field=models.TextField(verbose_name='Причина обращения'),
        ),
        migrations.AlterField(
            model_name='guestemail',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='Работник?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='superuser',
            field=models.BooleanField(default=False, verbose_name='Админ?'),
        ),
    ]
