# Generated by Django 3.0.7 on 2021-05-16 19:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210429_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestemail',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79998887766', max_length=128, region=None, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+71112223344', max_length=128, region=None, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
